blog3/blog3/urls.py
from django.urls import path
from .views import index,post_detail,category_show,post_create,post_update,post_delete
app_name="blog3"
urlpatterns = [
    path('',index,name='index' ),
    path('create/',post_create,name='create' ),
    path('<str:slug>/update',post_update,name='update' ),
    path('<str:slug>/delete',post_delete,name='delete' ),
    
    path('<str:slug>',post_detail,name='detail' ),
    path('<str:slug>/category',category_show,name='category' ),
 
]

blog3/main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("blog3.urls")),
    path('users/',include("users.urls")),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

blog3/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views#djangonun kendi login ve logotunu kullanabilmek için
from .views import register


app_name="users"
urlpatterns = [
    path("login/",auth_views.LoginView.as_view(template_name="users/login.html"),name="login"),
    path('logout/',auth_views.LogoutView.as_view(template_name="users/logout.html"),name="logout"),
    path('register/',register,name="register")
]

blog3/blog3/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.
def user_directory_path(instance,filename):
    return'blog3/{0}/{1}'.format(instance.author.id,filename)



class Category(models.Model):
    name=models.CharField(max_length=20)
    image=models.ImageField(upload_to='cat',null=True,blank=True )
    slug=models.SlugField(blank=True, unique=True,)
   
    
    def __str__(self):
        return self.name
    







class Post(models.Model):
    
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    title=models.CharField(max_length=300)
    content=RichTextField()
    published_date=models.DateTimeField(auto_now_add=True)
    image=models.ImageField(upload_to=user_directory_path,null=True,blank=True )
    status=models.ForeignKey(Category,on_delete=models.CASCADE)
    #farklı kullanıcılar aynı resmi paylaştıgında adlandırma farklı olmalı ona da bir bak
    slug=models.SlugField(blank=True, unique=True)
    
   
    
    def __str__(self):
        return self.title
    
    def comment_count(self):
        return self.comment_set.all().count()
    
    def comments(self):
        return self.comment_set.all()
    
    class Meta:
        ordering =['-published_date','id']
        
class Comment(models.Model):
    #user=models.ForeignKey(User,on_delete=models.CASCADE)
    name=models.CharField(max_length=100,verbose_name='Name',default='Name')
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    time_stamp=models.DateTimeField(auto_now_add=True)
    content=RichTextField()
    approved_comment=models.BooleanField(default=False)
    
    def approve(self):
        self.approved_comment=True
        self.save()
        
    def approved_comments(self):
        return self.comments.filter(approved_comment=True)
    
    def __str__(self):
        return self.name
                             

blog3/users/models.py
from django.db import models

# Create your models here.

blog3/blog3/forms.py
from django import forms
from .models import Comment, Post,Category
class PostForm(forms.ModelForm):
    status=forms.ModelChoiceField(queryset=Category.objects.all(),empty_label="Select Category")
    
    class Meta:
        model=Post
        fields=["title","image","content","status"]



class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=["name","content"]#kullanıcıya sunulacak kısım


#{{form.media}}

blog3/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):#UserCreation form san inherit ediyoruz.Zaten UserCreation modeli içinde passwor1 ve password2 işlemleri mevcut biz extra User modelinden de username ve email alanlarını da alıp bu Register formuna dahil ediyoruz
    email=forms.EmailField()#email alanını zorunlu kılmak için
    class Meta:
        model=User
        fields=("username","email")
    def clean_email(self):
        email=self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Please use another Email, that one already taken ")
        return email

blog3/blog3/views.py
from django.core import paginator
from django.shortcuts import render,redirect,get_object_or_404,Http404
from .models import Comment, Post,Category
from .forms import CommentForm,PostForm
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger#peginationun görülmesi için import etttiğimiz kütüphaneler
from django.db.models import Q#aramalar için
from django.contrib.auth.decorators import login_required
from django.contrib import messages



# Create your views here.
def index(request):
    recent_posts=Post.objects.all().order_by("-published_date")[:2]
   
    post_list=Post.objects.all()
    
    #categories
    cats=Category.objects.all()
    
    #search
    query=request.GET.get('q')
    if query:
        post_list=post_list.filter(
            Q(title__icontains=query )| Q(content__icontains=query)   #| Q(user_first_name__icontains=query)  
        ).distinct()
    
    #pegination
    paginator=Paginator(post_list,3)
    page_number=request.GET.get('page')
    page_obj=paginator.get_page(page_number)
    
    
    

           
    context={
        "page_obj":page_obj,
        "cats":cats,
        "recent_posts":recent_posts,
        
        
    }
   
    return render(request,'index.html',context)


# def search(request):
#     posts=Post.object.all()
#     query=request.GET.get('q')
#     if query:
#         posts=posts.filter(
#             Q(title__icontains=query ) |Q(status__icontains=query) 
#         ).distinct()
#     context={
#         "posts":posts
#     }
#     return render(request,'footer.html',context)
@login_required
def post_create(request):
    
    form=PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post=form.save(commit=False)
        post.author=request.user
        post.save()
        return redirect("blog3:index")
    context={
        "form":form
    }
    return render(request,'post_create.html',context)

@login_required    
def post_update(request,slug):
    if  not request.user.is_authenticated():
        return Http404()
    post=get_object_or_404(Post,slug=slug)
    if request.user.id!=post.author.id:
        return redirect("index")
    form=PostForm(request.POST or None, request.FILES or None,instance=post)
    if form.is_valid():
        form.save()
        return redirect("blog3:index")
    context={
        "post":post,
        "form":form
    }
       
    return render(request,"post_create.html",context)





def post_detail(request,slug):
    
    form=CommentForm()
    obj=get_object_or_404(Post, slug=slug)
    if request.method=="POST":
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            #comment.user=request.user
            comment.post=obj
            comment.save()
            return redirect("blog3:detail",slug=slug)
    context={
        "post":obj,
        "form":form,
    }
    return render(request,'post_detail.html',context)

@login_required
def post_delete(request,slug):
    
    post=get_object_or_404(Post,slug=slug)
    if request.user.id!=post.author.id:
        return redirect("blog3:index")
    else:
        post.delete()
        return redirect("blog3:index")
        
   

@login_required
def comment_approved(request,slug):
    comment=get_object_or_404(Comment,slug=slug)
    comment.approve()
    return redirect('blog3:detail',slug=comment.post.slug)#slug=slug

@login_required
def comment_remove(request,slug):
    comment=get_object_or_404(Comment,slug=slug)
    comment.delete()
    return redirect('blog3:detail',slug=comment.post.slug)
    

    
    



def category_show(request,slug):
    
    cat=get_object_or_404(Category,slug=slug)
    items=Post.objects.filter(status=cat)
    context={
        "cat":cat,
        "items":items,
        
    }
    return render(request,'categories.html',context)

blog3/users/views.py
from django.shortcuts import render,redirect
from .forms import RegistrationForm

# Create your views here.
def register(request):
    form=RegistrationForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("users:login")
    context={
        "form":form
    }
    return render(request,'users/register.html',context)

blog3/templates/base.html
{%load static%}
{%include 'header.html'%}
{%block content%}

{%endblock content%}

{%include 'footer.html'%}

blog3/templates/categories.html
{%extends 'base.html'%}{%load static%}
{%block content%}
<br><br>
<section class="top-recipe spad">
    <div class="section-title">
        <h5>{{cat.name}}</h5>
    </div>
    <div class="container po-relative">




        <div class="plus-icon">
            <i class="fa fa-plus"></i>
        </div>
    <div class="container po-relative">
        <div class="row">
            {%for post in items%}

            <div class="col-lg-4">
                <div class="top-recipe-item large-item">
                    <div class="top-recipe-img set-bg" data-setbg="{{post.image.url}}">
                        <a href="{%url 'blog3:detail' post.slug%}"></a><i class="fa fa-plus"></i></a>
                    </div>
                    <div class="top-recipe-text">
                        <div class="cat-name">{{post.status}}</div>
                        <a href="#">
                            <h4><a href="{%url 'blog3:detail' post.slug%}">{{post.title}}</a></h4>
                        </a>
                        <p>{{post.content|safe|truncatechars:150}}</p>
                    </div>
                </div>
            </div>

            {%endfor%}




        </div>
    </div>
</section>







<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form" method="GET" action="" role="search">
            <input type="text" id="search-input" placeholder="Search here....." name="q" value="{{request.GET.q}}">

        </form>
    </div>
</div>



{%endblock content%}

blog3/templates/footer.html
{%load static%}

<!-- Categories Filter Section End -->





<footer class="footer-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-5">
                <div class="fs-left">
                    <div class="logo">
                        <a href="#">
                            <img src="{%static 'img/footer-logo.png'%}" alt="">
                        </a>
                    </div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo
                        viverra maecenas accumsan lacus vel facilisis.</p>
                </div>
            </div>
            <div class="col-lg-6 offset-lg-1">
                <form action="#" class="subscribe-form">
                    <h3>Subscribe to our newsletter</h3>
                    <input type="email" placeholder="Your e-mail">
                    <button type="submit">Subscribe</button>
                </form>
                <div class="social-links">
                    <a href="#"><i class="fa fa-instagram"></i><span>Instagram</span></a>
                    <a href="#"><i class="fa fa-pinterest"></i><span>Pinterest</span></a>
                    <a href="#"><i class="fa fa-facebook"></i><span>Facebook</span></a>
                    <a href="#"><i class="fa fa-twitter"></i><span>Twitter</span></a>
                    <a href="#"><i class="fa fa-youtube"></i><span>Youtube</span></a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="copyright-text">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

<!-- Search model -->

<!-- Search model end -->

<!-- Js Plugins -->
<script src="{%static 'blog3/js/jquery-3.3.1.min.js'%}"></script>
<script src="{%static 'blog3/js/bootstrap.min.js'%}"></script>
<script src="{%static 'blog3/js/jquery.slicknav.js'%}"></script>
<script src="{%static 'blog3/js/jquery.nice-select.min.js'%}"></script>
<script src="{%static 'blog3/js/mixitup.min.js' %}"></script>
<script src="{%static 'blog3/js/main.js'%}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>

blog3/templates/header.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Yummy | Django</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=PT+Sans:400,700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Css Styles -->
    <link rel="stylesheet" href="{%static 'blog3/css/bootstrap.min.css'%}" >
    <link rel="stylesheet" href="{%static 'blog3/css/font-awesome.min.css'%}" >
    <link rel="stylesheet" href="{%static 'blog3/css/nice-select.css'%}" >
    <link rel="stylesheet" href="{%static 'blog3/css/slicknav.min.css'%}" >
    <link rel="stylesheet" href="{%static 'blog3/css/style.css'%}" >
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="container">
            <div class="logo">
                
                <a href="#"><img src="{% static 'blog3/img/logo.png'%}" alt=""></a>
            </div>
            <div class="nav-menu">
                <nav class="main-menu mobile-menu">
                    <ul>
                        <li class="active"><a href="{%url 'blog3:index'%}">Home</a></li>
                        <li><a href="#">About Me</a>
                            <!-- <ul class="sub-menu">
                                <li><a href="#">About Me</a></li>
                                <li><a href="#">Categories</a></li>
                                <li><a href="#">Recipe</a></li>
                                <li><a href="#">Blog</a></li>
                                <li><a href="#">Contact</a></li>
                            </ul> -->
                        </li>
                        {%if request.user.is_authenticated%}
                        <li><a href="{%url 'blog3:create'%}">New Post</a></li> 
                        <li><a href="{%url 'users:logout'%}">Logout</a></li>
                       
                         {%else%}
                        <li><a href="{%url 'users:login'%}">Login</a></li>  
                        <li><a href="{%url 'users:register'%}">Register</a></li>  
                        {%endif%}
                    </ul>
                </nav>
                <div class="nav-right search-switch">
  
                        
                        <i class="fa fa-search"></i>
                
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>

blog3/templates/index.html
{%extends 'base.html'%}{%load static%}
{%block content%}

<!-- Top Recipe Section Begin -->
<br><br>

<section class="top-recipe spad">
    <div class="section-title">
        <h5>Top Recipes this Week</h5>
    </div>
    <div class="container po-relative">




        <div class="plus-icon">
            <i class="fa fa-plus"></i>
        </div>








        <div class="row">
            {%for post in page_obj%}

            <div class="col-lg-4">
                <div class="top-recipe-item large-item">
                    <div class="top-recipe-img set-bg" data-setbg="{{post.image.url}}">
                        <a href="{%url 'blog3:detail' post.slug%}"><i class="fa fa-plus"></i></a>
                    </div>
                    <div class="top-recipe-text">
                        <div class="cat-name">{{post.status}}</div>
                        <a href="{%url 'blog3:detail' post.slug%}">
                            <h4>{{post.title}}</h4>
                        </a>
                        <p>{{post.content|safe|truncatechars:150}}</p>
                    </div>
                </div>
            </div>

            {%endfor%}

            <!-- pegination -->

            <!-- -------------------------------------------------- -->
            
            <!-- ----------------------- -->
            <div class="pagination">
                <span class="step-links">
                    {%if page_obj.has_previous%}
                    <a href="?page=1">&laquo;first</a>
                    <a href="?page={{page_obj.previous_page_number}}">previous</a>
                    {%endif%}
                    <span class="current">
                        Page{{page_obj.number}} of {{page_obj.paginator.num_pages}}.
                    </span>
                    {%if page_obj.has_next%}
                    <a href="?page={{page_obj.next_page_number}}">next</a>
                    <a href="?page={{page_obj.paginator.num_pages}}">last&raquo;</a>
                    {%endif%}
                   
                    
                </span>
            </div>







            <!-- ------------------------------------------ -->



        </div>
    </div>
</section>

<br><br>


<section class="similar-recipe top-recipe spad">

    <div class="section-title">
        <h5>Categories</h5>
    </div>
    <div class="container">
        
        <div class="row">
            {%for cat in cats%}
            <div class="col-lg-3 col-md-6">
                
                <div class="similar-item">
                    <a href="{%url 'blog3:category' cat.slug%}"><img src="{{cat.image.url}}" alt=""></a>
                    <div class="similar-text">
                        <a href="{%url 'blog3:category' cat.slug%}"><div class="cat-name">{{cat.name}}</div></a>
                        
                    </div>
                    
                </div>
                
               

            </div>
            {%endfor%}
        </div>
        

    </div>

    




</section> 


<!-- Feature Recipe Section Begin -->
<section class="feature-recipe">
    <div class="section-title">
        <h5>Recent Posts</h5>
    </div>

    <div class="container po-relative">
        
        <div class="row">
            {%for recent in recent_posts%}
            <div class="col-lg-6">
                
                <div class="fr-item">
                    
                    <div class="fr-item-img">
                        <img src="{{recent.image.url}}" alt="">
                    </div>
                    <div class="fr-item-text">
                      <a href="{%url 'blog3:detail' recent.slug%}"><h4>{{recent.title}}</h4></a>  
                        <small>({{recent.published_date}})</small>
                        <p>{{recent.content|safe|truncatechars:150}}</p>
                    </div>
                    
                </div>
                
            </div>
            {%endfor%}
            <!-- <div class="col-lg-6">
                <div class="fr-item">
                    <div class="fr-item-img">
                        <img src="{%static 'blog3/img/feature-2.jpg'%}" alt="">
                    </div>
                    <div class="fr-item-text">
                        <h4>Sunday Brunch: Spaghetti and Eggs Recipe</h4>
                        <p>{{post.content|safe|truncatechars:150}}</p>
                    </div>
                </div>
            </div> -->
          
        </div>
    </div>
</section>





















<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form" method="GET" action="" role="search">
            <input type="text" id="search-input" placeholder="Search here....." name="q" value="{{request.GET.q}}">

        </form>
    </div>
</div>


{%endblock content%}
<!-- ckeditör kullanabilmek için {{post.content|safe|linebreaks|truncatechars:80}} -->

blog3/templates/post_create.html
{%extends 'base.html'%}{%load static%}
{%load crispy_forms_tags %}
{%block content%}
<br><br>
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Blog Post</h3>
        <hr>
<form action="" method="POST" enctype="multipart/form-data" >
    {%csrf_token%}  
    {{form|crispy}}
    {{form.media}}
    <br>
    <button type="submit" class="btn btn-outline-info">POST</button>
</form>
</div>
</div>
<br><br>
{%endblock content%}

blog3/templates/post_detail.html
{%extends 'base.html'%}{%load static%}
{%load crispy_forms_tags %}
{%block content%}
<div class="hero-search set-bg" data-setbg="{{post.image.url}}">
    <div class="container">
        <div class="filter-table">
            <form action="#" class="filter-search">

                <button type="submit">{{post.status}}</button>

            </form>
        </div>
    </div>
</div>
<section class="blog-section-spad">
    <div class="recipe-top">
        <div class="container-fluid">
            <div class="recipe-title">
                <h2>{{post.title}}</h2>

                <ul class="tags">
                    <li>{{post.published_date}}</li>

                </ul>
            </div>



            <div class="blog-pic">
                <div class="container ">
                    <div class="row">
                        <div class="col-lg-15">
                            <div class="top-recipe-item large-item">
                                <div class="top-recipe-img set-bg" data-setbg="{{post.image.url}}">
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>



    <div class="container">
        <div class="blog-text">
            <div class="blog-desc">
                <p>{{post.content|safe|linebreaks}}</p>

                <div class="blog-quote">
                    <i class="fa fa-quote-left"></i>
                    <p>{{post.author}}</p>
                    {%if request.user.is_authenticated%}
                    
                    <p><a href="{%url 'blog3:update' post.slug %}" class="btn btn-success" role="button">Update</a>
                        <a href="{%url 'blog3:delete' post.slug %}" class="btn btn-danger" role="button">Delete</a>
                    </p>
                    {%endif%}
                  
                </div>
            </div>
            

                    
               
            <div class="blog-comment">
                <h3>Comments ({{post.comment_count}})</h3>
                {%for comment in post.comments%}
                <div class="single-comment">
                    {%if comment.approved_comment%}

                    <ul>
                        <li>comment by {{comment.name}}</li>
                        <li>{{comment.time_stamp|timesince}} ago</li>

                    </ul>
                    <p>{{comment.content|safe}}</p>


                </div>
                {%endif%}
                {%endfor%}
            </div>

            <form action="#" class="comment-form" method="post">
                {%csrf_token%}
                <h3>Leave a Comment</h3>
                <div class="row">


                    {{form|crispy}}
                    {{form.media}}
                </div>

                <button type="submit">Post</button>
            </form>
        </div>
    </div>







</section>
<br><br><br>







{%endblock content%}

blog3/templates/users/login.html
{%extends 'base.html'%}{%load static%}
{%load crispy_forms_tags %}
{%block content%}
<br><br>
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Login Form</h3>
        <hr>
<form action="" method="POST" enctype="multipart/form-data" >
    {%csrf_token%}  
    {{form|crispy}}
    
    <br>
    <button type="submit" class="btn btn-outline-info">LogIn</button>
</form>
</div>
</div>
<br><br>
{%endblock content%}

blog3/templates/users/register.html
{%extends 'base.html'%}{%load static%}
{%load crispy_forms_tags %}
{%block content%}
<br><br>
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Register Form</h3>
        <hr>
<form action="" method="POST" enctype="multipart/form-data" >
    {%csrf_token%}  
    {{form|crispy}}
    
    <br>
    <button type="submit" class="btn btn-outline-info">Register</button>
</form>
</div>
</div>
<br><br>
{%endblock content%}